### ISSUE TITLE
Show possible font optimisations

### ISSUE THREAD

**Issue by bramstein** [Wakamai-Fondue/wakamai-fondue-site#17]
Most fonts have some extra data that isn't all that relevant for web fonts (for example some CMAP formats, most name table entries, non-standard tables.) and can be safely stripped out, thereby reducing the file size.

There are other suggestion that could be made as well: for example if someone uploads a WOFF file, the tool could show how much smaller the font could be using WOFF2.

**Comment by RoelN** [comment]
I think this is out of scope, so I'm closing this. Still thanks, @bramstein!

**Comment by bramstein** [comment]
I demand a refund!
